use KRYPTON;
show tables;
drop table contact;
desc table contact;
CREATE TABLE `krypton`.`contact` (
  `S_NO` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `AGE` INT NOT NULL,
  `PHONE_NUMBER` BIGINT(13) NOT NULL,
  `DOB` DATE NOT NULL,
  `GENDER` VARCHAR(1) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NOT NULL,
  `WORK` VARCHAR(40) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`S_NO`, `PHONE_NUMBER`));

SELECT*FROM CONTACT;
SHOW WARNINGS;
DELETE FROM CONTACT;
INSERT INTO CONTACT(NAME,AGE,PHONE_NUMBER,DOB,GENDER,EMAIL_ID,WORK,ADDRESS) VALUES("PIYUSH",19,9468472022,"2002-04-24","M","YNR24PIYUSH@GMAIL.COM","STUDENT","ENCLAVE");